pipeline {
  agent any

  tools {
    maven 'Maven 3'
    jdk 'JDK 17'
  }

  stages {
    stage('Checkout') {
      steps {
        git 'git@github.com:jicool91/test1.git'
      }
    }

    stage('Build') {
      steps {
        sh 'mvn clean install -DskipTests'
      }
    }
  }
}
