spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:postgresql://localhost:5432/marketflow
    username: mf_user
    password: mf_pass

  # Конфигурация Liquibase
  liquibase:
    enabled: false
    change-log: classpath:/db/liquibase-config.xml

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8085

api:
  key: "123456"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs